### ISSUE TITLE
iHandler "submit_http_post" is not uploading files, throws error

### ISSUE THREAD

**Issue by JBAnderson** [DinoTools/dionaea#125]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.6.0 
Compiled on Linux/x86_64 at Jun 12 2017 02:39:00 with gcc 4.8.4 
Started on XXXXXXXX running Linux/x86_64 release 4.4.0-79-generic

```

##### CONFIGURATION

submit_http_post.yaml
IP redacted
```
- name: submit_http_post
  config:
    submit:
      file_upload:
        urls:
          - http://123.456.78.90:8080/upload
        #  - http://example.com/file.php
        field_values:
           submit: "Upload file"
        file_fieldname: upload_file

```

##### OS / ENVIRONMENT

 - Ubuntu 14.04

##### SUMMARY

Trying to get submit_http_post to send files to my server. All other incident handlers I have configured are working great, however submit_http_post does not send the file and throws an error in dionaea.log
##### STEPS TO REPRODUCE

Trigger a unique download while submit_http_post is active

##### EXPECTED RESULTS

Upload request including file is sent to the url in the submit_http_post configuration
##### ACTUAL RESULTS

No upload request is sent, error is thrown in dionaea.log

```
[05072017 03:29:34] submit_http_post dionaea/submit_http_post.py:52-debug: submitting file
[05072017 03:29:34] python module.c:1035-warning: ValueError at ValueError('too many values to unpack (expected 2)',)
[05072017 03:29:34] python module.c:1060-warning: /opt/dionaea/lib/dionaea/python/dionaea/submit_http_post.py:65 in handle_incident
[05072017 03:29:34] python module.c:1061-warning:        for k, v in to.get("field_values", {}):
[05072017 03:29:34] python module.c:1060-warning: binding.pyx:1217 in dionaea.core.c_python_ihandler_cb (binding.c:12641)
[05072017 03:29:34] python module.c:1061-warning:        None
[05072017 03:29:34] python module.c:812-debug: traceable_ihandler_cb incident 0x1d72ab0 ctx 0x7f6f7f4bf588
[05072017 03:29:34] python module.c:812-debug: traceable_ihandler_cb incident 0x289d4d0 ctx 0x7f6f7f4bf308
[05072017 03:29:34] python module.c:812-debug: traceable_ihandler_cb incident 0x289d4d0 ctx 0x7f6f7f4bf548
[05072017 03:29:34] python module.c:812-debug: traceable_ihandler_cb incident 0x289d4d0 ctx 0x7f6f7f4bf588


```
