### ISSUE TITLE
[ASK] smb.py /dionaea/smb/smb.py:790: Attempt to register ....

### ISSUE THREAD

**Issue by n0n3n0w** [DinoTools/dionaea#238]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.8.0-24-g4159025 
Compiled on Linux/x86_64 at Oct  2 2018 22:01:16 with gcc 5.4.0 20160609 
Started on ubuntu running Linux/x86_64 release 4.15.0-36-generic

```

##### CONFIGURATION

```
- name: smb
  config:

    ## Generic setting ##

    # 1:"Windows XP Service Pack 0/1",
    # 2:"Windows XP Service Pack 2",
    # 3:"Windows XP Service Pack 3",
    # 4:"Windows 7 Service Pack 1",
    # 5:"Linux Samba 4.3.11"
    os_type: 4

     # Additional config
    primary_domain: Development
    oem_domain_name: Development
    server_name: DEVELOPMENT-SERVER

     ## Windows 7 ##
    native_os: Windows 7 Professional 7600
    native_lan_manager: Windows 7 Professional 6.1
    shares:
      ADMIN$:
        comment: Remote Admin
        path: C:\\Windows
        type: disktree
      C$:
        coment: Default Share
        path: C:\\
        type:
          - disktree
          - special
      IPC$:
        comment: Remote IPC
        type: ipc
      Printer:
        comment: Microsoft XPS Document Writer
        type: printq

     ## Samba ##
#    native_os: Windows 6.1
#    native_lan_manager: Samba 4.3.11
#    shares:
#      admin:
#        comment: Remote Admin
#        path: \\home\\admin
#        type: disktree
#      share:
#        coment: Default Share
#        path: \\share
#        type: disktree
#      IPC$:
#        comment: Remote IPC
#        path: IPC Service
#        type: ipc
#      Printer:
#        comment: Printer Drivers
#        type: printq


```

##### OS / ENVIRONMENT

 - Ubuntu 16.04
 

##### SUMMARY

I tried to attack dionaea honeypot using metasploit with smb vulnerability. But, the dionaea always brings up the message "[09102018 03:37:01] SMB /dionaea/smb/smb.py:790: Attempt to register ec04e01a-e50f-412c-8f8c-2daa4b572bb9 failed, UUID does not exist or is not implemented". I have no idea that if its acctually a bug or not. i just wanna ask but with bug format. i include screenshot of the bug.  

![Dionaea uuid](https://imgur.com/a/Kl3061q)
![smb.py ss](https://imgur.com/a/EPrjXoP)

##### STEPS TO REPRODUCE

Dionaea running with default configuration. i start dionaea with /opt/dionaea/bin/dionaea

##### EXPECTED RESULTS

dionaea runs normally, receiving malware that is stored in binaries.
##### ACTUAL RESULTS

```

```
