### ISSUE TITLE
smb NT_STATUS_CONNECTION_DISCONNECTED

### ISSUE THREAD

**Issue by nikAizuddin** [DinoTools/dionaea#333]
##### ISSUE TYPE

 - Bug Report

##### DIONAEA VERSION

```
Dionaea Version 0.11.0 
Compiled on Linux/x86_64 at Aug 26 2022 09:06:10 with gcc 7.5.0 
Started on dionaea-pod running Linux/x86_64 release 5.18.13-100.fc35.x86_64


Dionaea Version 0.11.0 
Compiled on Linux/x86_64 at Aug 26 2022 09:06:10 with gcc 7.5.0 
Started on dionaea-pod running Linux/x86_64 release 5.18.13-100.fc35.x86_64
```

##### CONFIGURATION

`smb.yaml`:
```
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

- name: smb
  config:

    ## Generic setting ##

    # 1:"Windows XP Service Pack 0/1",
    # 2:"Windows XP Service Pack 2",
    # 3:"Windows XP Service Pack 3",
    # 4:"Windows 7 Service Pack 1",
    # 5:"Linux Samba 4.3.11"
    os_type: 5

    primary_domain: Test
    oem_domain_name: Test
    server_name: TEST-SERVER

    native_os: Windows 7 Professional 7600
    native_lan_manager: Windows 7 Professional 6.1
    shares:
      ADMIN$:
        comment: Remote Admin
        path: C:\\Windows
        type: disktree
      C$:
        comment: Default Share
        path: C:\\
        type:
          - disktree
          - special
      IPC$:
        comment: Remote IPC
        type: ipc
      Printer:
        comment: Microsoft XPS Document Writer
        type: printq

    ## Samba ##
    native_os: Windows 6.1
    native_lan_manager: Samba 4.3.11
    shares:
      admin:
        comment: Remote Admin
        path: \\home\\admin
        type: disktree
      share:
        comment: Default Share
        path: \\share
        type: disktree
      IPC$:
        comment: Remote IPC
        path: IPC Service
        type: ipc
      Printer:
        comment: Printer Drivers
        type: printq
```

##### OS / ENVIRONMENT

 - Ubuntu 18.04 (Container)

##### SUMMARY

Unable to connect via `smbclient` command.

##### STEPS TO REPRODUCE

Execute:
```
smbclient --user=WORKGROUP/foo //127.0.0.1/admin
```

##### EXPECTED RESULTS

Should be able to enter the remote share

##### ACTUAL RESULTS

`smbclient` returns the following error:
```
protocol negotiation failed: NT_STATUS_CONNECTION_DISCONNECTED
```

However, in Dionaea log there are no error / warning
